accelerator: null
accumulate_grad_batches: 1
adam_epsilon: 1.0e-08
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
cuda_ids: 0
data_dir: ../data/ASTE/V2/14lap
default_root_dir: null
deterministic: false
distributed_backend: null
do_train: true
eval_batch_size: 1
fast_dev_run: false
flush_logs_every_n_steps: 100
gpus: 1
gradient_clip_algorithm: norm
gradient_clip_val: 1.0
learning_rate: 3.0e-05
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr_scheduler: linear
max_epochs: 10
max_seq_length: -1
max_steps: null
max_time: null
min_epochs: null
min_steps: null
model_name_or_path: D:/class9/bert-local/models--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_d: 64
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_table_layers: 2
num_workers: 4
output_dir: ../output/ASTE/V2/14lap/
overfit_batches: 0.0
plugins: null
precision: 16
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
seed: 40
seq2mat: tensorcontext
span_pruning: 0.3
stochastic_weight_avg: false
sync_batchnorm: false
table_encoder: resnet
terminate_on_nan: false
tpu_cores: null
track_grad_norm: -1
train_batch_size: 2
truncated_bptt_steps: null
val_check_interval: 1.0
warmup_steps: 100
weight_decay: 0.01
weights_save_path: null
weights_summary: top
